#!/bin/sh

/etc/init.d/mysql start

sleep 5

mysql -u root -e " \
  SET PASSWORD = PASSWORD('root'); \
  UPDATE mysql.user SET password = PASSWORD('root') WHERE user = 'root'; \

/etc/init.d/mysql stop